chore(feature-flag): default doNotEval SPeL expression to On
spinnaker/kork pull request #1028
Opened 2023-03-21 08:48 UTC by ciurescuraul

Enabling “doNotEval” SPeL expression by default. This feature is disabled only when the flag is set explicitly to false.

2023-03-21 10:34 UTC, ovidiupopa07 approved these changes
lgtm

2023-03-21 16:25 UTC, ovidiupopa07 commented
> Please update the PR description and commit message to `feat(doNoEval)` since this is a behavior change. But then also, what's the reasoning behind this change? Please include that as well in the PR description + commit message.
> 
> And then finally, I don't think it's quite time to do this. [This release note](https://github.com/spinnaker/spinnaker.io/blob/1566d78587759ed118765e21490b3f1a2b14cd98/content/en/docs/releases/next-release-preview/index.md#donoteval-spel-helper) says the flag is new for 1.30, but 1.30 hasn't been released yet. Let's wait until it has before merging this.

hi @dbyron-sf . The initial [PR](https://github.com/spinnaker/kork/pull/981) was back-ported to 1.28 and 1.29. The intention here is to enable this feature by default in 1.30 instead of manually opting in for it

2023-03-21 17:55 UTC, dbyron-sf commented
> > Please update the PR description and commit message to `feat(doNoEval)` since this is a behavior change. But then also, what's the reasoning behind this change? Please include that as well in the PR description + commit message.
> > And then finally, I don't think it's quite time to do this. [This release note](https://github.com/spinnaker/spinnaker.io/blob/1566d78587759ed118765e21490b3f1a2b14cd98/content/en/docs/releases/next-release-preview/index.md#donoteval-spel-helper) says the flag is new for 1.30, but 1.30 hasn't been released yet. Let's wait until it has before merging this.
> 
> hi @dbyron-sf . The initial [PR](https://github.com/spinnaker/kork/pull/981) was back-ported to 1.28 and 1.29. The intention here is to enable this feature by default in 1.30 instead of manually opting in for it. As per the [RFC](https://github.com/spinnaker/governance/pull/303) we should enable a feature in the next LTS (since it was back-ported to previous LTS releases)

OK, it helps to know the feature has already been released.  I don't see where https://github.com/spinnaker/governance/pull/303 says "we should enable a feature in the next LTS", but even if it does, I'd still like to know the specific reason for doing it for this flag.  Like, what are the consequences for changing this flag on existing spinnaker users/installations/pipelines/etc. ?  Who is it going to break vs. who is it going to help.  Or perhaps put another way, I'd like to see the release note describing this change.

As a bit of an aside, https://github.com/spinnaker/governance/pull/303 does say

> We propose that this change take effect immediately in the backport
> policy and relevant contributor documentation be updated to describe
> the facilities for feature flagging in the project.

but I don't think https://spinnaker.io/docs/community/contributing/code/releasing/#release-branch-patch-criteria has been updated.

2023-03-22 09:42 UTC, ciurescuraul commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
> +    private boolean enabled = true;
this change has been addressed. thx @dbyron-sf and @ovidiupopa07  for the comments!

2023-03-22 10:03 UTC, ovidiupopa07 requested changes

2023-03-22 10:03 UTC, ovidiupopa07 commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
> +  public FeatureFlag getDoNotEvalSpel() {
I would prefer having a fluent setter in the `FeatureFlag` class like this
```
class FeatureFlag {
  private enabled;

  public void setEnabled(boolean enabled) {
     this.enabled = enabled'
     return this;
  }
}
```

that can be used in `ExpressionProperties` like this `private final FeatureFlag doNotEvalSpel = new FeatureFlag().setEnabled(true);`

2023-03-23 19:49 UTC, dbyron-sf commented
> I guess the worst issue that could happen is the pipeline will not work as expected.

This is a bit of an unsatisfying answer, but with SpEL expressions it may be the best we can do.  It does look like https://spinnaker.io/docs/releases/next-release-preview/#donoteval-spel-helper could use a tweak when this PR goes in.  Would you mind putting up a PR with those changes?  At that point I'm OK with this going in, though I still think it may not make 1.30.0.

2023-03-24 08:39 UTC, ovidiupopa07 commented
> > I guess the worst issue that could happen is the pipeline will not work as expected.
> 
> This is a bit of an unsatisfying answer, but with SpEL expressions it may be the best we can do. It does look like https://spinnaker.io/docs/releases/next-release-preview/#donoteval-spel-helper could use a tweak when this PR goes in. Would you mind putting up a PR with those changes? At that point I'm OK with this going in, though I still think it may not make 1.30.0.

https://github.com/spinnaker/spinnaker.io/pull/317 -> PR for the docs

2023-03-30 13:19 UTC, dbyron-sf commented
Now that 1.30.0 is out, https://github.com/spinnaker/spinnaker.io/pull/317 could use an update @ovidiupopa07 , and I think this is good to go.

2023-03-30 16:46 UTC, ciurescuraul commented
Created new PR with updated docs for Release 1.31 -> [spinnaker/spinnaker.io#324](https://github.com/spinnaker/spinnaker.io/pull/324)

2023-03-30 17:27 UTC, dbyron-sf approved these changes

2023-03-30 17:27 UTC, dbyron-sf commented
@mergifyio update

2023-03-30 17:28 UTC, dbyron-sf commented
Looks like this needs a rebase, but otherwise it looks good to go to me.  You agree @ovidiupopa07 ?  I pushed the button too fast and merged https://github.com/spinnaker/spinnaker.io/pull/324 already...

2023-03-30 17:45 UTC, dbyron-sf commented on gradle.properties
> +spinnakerGradleVersion=8.26.0
This seems fishy as the [HEAD of master](https://github.com/spinnaker/kork/blob/7e6e0d496f2bae8e9828ff84c7a5ac1844f05053/gradle.properties#L3) is already using 8.26.0.

2023-03-30 17:58 UTC, ciurescuraul commented on gradle.properties
> +spinnakerGradleVersion=8.26.0
> This seems fishy as the [HEAD of master](https://github.com/spinnaker/kork/blob/7e6e0d496f2bae8e9828ff84c7a5ac1844f05053/gradle.properties#L3) is already using 8.26.0.

Created new PR to eliminate any doubt ->  https://github.com/spinnaker/kork/pull/1030

2023-03-30 18:04 UTC, closed without merging

2023-03-30 18:05 UTC, dbyron-sf commented on gradle.properties
> +spinnakerGradleVersion=8.26.0
Bummer...then we lose all the context.  Sure there's no way to bring this back to life?

2023-03-31 07:45 UTC, ciurescuraul commented on gradle.properties
> +spinnakerGradleVersion=8.26.0
Didn't realize at the moment what the impact would be. 
It doesn't seem to let me reopen this one,  [the new PR #1030](https://github.com/spinnaker/kork/pull/1030) has a reference to the [old PR #1028](https://github.com/spinnaker/kork/pull/1028). I hope this helps