Bumped aws sdk version for FIPS compliance
spinnaker/kork pull request #1043
Opened 2023-04-05 15:55 UTC by cs-simental

Version 1.12.399 is the lowest version that enables FIPS endpoints for GovCloud (US) regions in SDK

2023-04-05 16:04 UTC, dbyron-sf requested changes
I'm surprised this built.  Until version 1.12.399 of https://github.com/Netflix/awsobjectmapper exists, I don't think this is gonna work.  That repo is totally open to contributions though, so please make a PR there.

2023-04-05 16:56 UTC, cs-simental commented
@dbyron-sf  made a pull request for https://github.com/Netflix/awsobjectmapper

https://github.com/Netflix/awsobjectmapper/pull/116

do you know who I may reach to give a look to the request?

2023-04-05 16:57 UTC, dbyron-sf commented
Thanks.  They're usually pretty prompt.

2023-04-17 19:34 UTC, dbyron-sf commented
@mergifyio update

2023-04-17 19:35 UTC, dbyron-sf commented
@cs-simental could you rebase please?  Also would be great if you can link to some docs showing 1.12.399 as the minimum version for govcloud fips compliance.

2023-04-17 22:27 UTC, cs-simental commented
@dbyron-sf rebased.

Link to FIPS documentation in was-java-sdk:
https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#112399-2023-02-02

2023-04-17 22:34 UTC, dbyron-sf commented
Thanks @cs-simental .  Can you also let us know where you've tested this please.

2023-04-20 23:52 UTC, Avi1235 commented
Hello 👋  updating the sdk alose helps with Configuring lambda SnapStart as it was introduced in [1.12.351](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#112351-2022-11-28)

see issue: https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/issues/128

2023-05-11 22:33 UTC, mattgogerly commented
> Hello 👋 updating the sdk also helps with Configuring lambda SnapStart as it was introduced in [1.12.351](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#112351-2022-11-28)
> 
> see issue: [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#128](https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/issues/128)

Thanks for highlighting this - we're working on moving the Lambda plugin into the main codebase and snapstart was on my list of things to add once that effort was done.

2025-10-02 03:24 UTC, closed without merging