feat(retrofit): move url attribute from SpinnakerHttpException to SpinnakerServerException
spinnaker/kork pull request #1110
Opened 2023-10-28 23:31 UTC by dbyron-sf

so it's available to exception handling code that currently has access to the url via RetrofitError.

2023-10-28 23:51 UTC, xibz requested changes
Overall looks good! One minor design consideration, but overall I like the approach

2023-10-28 23:51 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
> +        return new SpinnakerNetworkException(e);
This becomes easy to change too

```suggestion
        return new SpinnakerNetworkException(e.getMessage(), e.getCause(), e.getUrl());
```

2023-10-28 23:51 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +  public SpinnakerServerException(String message, Throwable cause, String url) {
I think with this new method signature, we can probably get rid of all the retrofit constructors tbh.

This will at least clean up the other exceptions and only require updating the one constructor in each other exception. This also keeps the `SpinnakerServerException` pretty agnostic to retrofit, which may be a better approach for now since we are only interested in the URL at this point. Further, if we do end up with more fields from retrofit in this particular class, we can revisit. However, let's keep it simple and just add the one field :)

2023-10-28 23:51 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
> +        return new SpinnakerConversionException(e);
```suggestion
        return new SpinnakerConversionException(e.getMessage(), e.getCause(), e.getUrl());
```

2023-10-28 23:51 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
> +        return new SpinnakerServerException(e);
```suggestion
        return new SpinnakerServerException(e.getMessage(), e.getCause(), e.getUrl());
```

2023-10-28 23:51 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +  public SpinnakerServerException(RetrofitError e) {
Then these go away and allows for only the `SpinnakerHttpException` to utilize all the retrofit fields

2023-10-29 22:38 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerConversionException.java
> +    setRetryable(false);
Oof, that sucks we need to add the false everywhere. May be nice to have a `implements NonRetryableException` or something like that, but that is separate from this PR

2023-10-29 22:46 UTC, xibz approved these changes
@dbyron-sf Thank you for the improvements! The javadocs are fantastic :) and really helped me understand the use cases.

I had one **very** minor nit comment, but this change looks really good :)

2023-10-29 22:46 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +  private final String url;
nit:
```suggestion
  @Getter private final String url;
```

2023-10-29 22:46 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +
```suggestion
```

2023-10-29 22:46 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +  public String getUrl() {
```suggestion
```

2023-10-29 22:46 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +    return this.url;
```suggestion
```

2023-10-29 22:46 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +  }
```suggestion
```

2023-10-29 22:53 UTC, xibz commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +import okhttp3.Request;
```suggestion
import lombok.Getter;
import okhttp3.Request;
```

2023-10-29 23:07 UTC, dbyron-sf commented on kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
> +  private final String url;
https://github.com/spinnaker/kork/pull/1110/commits/64f7673d409afd255dba0eaca76d45e0acf17250

2023-10-29 23:11 UTC, xibz approved these changes

2023-10-29 23:16 UTC, merged