feat(artifacts): always retrieve s3 artifacts even when artifact-store.s3.enabled is false
spinnaker/kork pull request #1120
Opened 2023-11-16 05:24 UTC by dbyron-sf

so changes to the config value while pipelines are executing, or actions on completed
pipelines (e.g. "Baked Manifest YAML") work without disruption.

Consider this sequence of events:

1. artifact-store.s3.enabled is true
2. a pipeline starts executing,
3. the pipeline execution context contains an artifact store reference
4. artifact-store.s3.enabled changes to false
5. the pipeline continues to execute and attempts to retrieve the artifact store reference

Before this change, step 5 would fail.  After this change, it succeeds.

This PR also removes the `artifact-store.enabled` flag, so now `artifact-store.s3.enabled` controls the behavior on it own.  This ends up requiring some bean naming tweaks in orca.

orca also now has the responsibility to call ArtifactStore.setInstance.

2023-11-16 22:10 UTC, xibz requested changes
Thanks for the PR, @dbyron-sf! Most of my comments are about moving things around and may trying a different approach. Let me know if you have any questions about the suggestions

2023-11-16 22:10 UTC, xibz commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
> +  public S3ArtifactStoreGetter s3ArtifactStoreGetter(
Rather than having the bucket ternary, can we do something like
`@ConditionalOnProperty(name = "artifact-store.s3")`?

Because if bucket is not specify, it will fail gets no matter what, so may make sense just to see if s3 is configured. If not, just don't create the getter.

I wonder if that also hold's true for the `artifactS3Client` bean as well, so it might clean that up too.

We could probably even move all this s3 bootstrapping to an `S3ArtifactStoreConfiguration` and just have the `@ConditionalOnProperty` on there

2023-11-16 22:10 UTC, xibz commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
> +  public NoopArtifactStoreStorer noopArtifactStoreStorer() {
If we allow for multiple storers this will need to change a little bit, but we can cross that bridge when we get there.

2023-11-16 22:15 UTC, xibz commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/NoopArtifactStoreStorer.java
> +public class NoopArtifactStoreStorer implements ArtifactStoreStorer {
I would probably also just change this to `NoopArtifactStore implements ArtifactStoreGetter, ArtifactStoreGetter` and do both

2023-11-16 22:15 UTC, xibz commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
> +  public S3ArtifactStoreGetter s3ArtifactStoreGetter(
Further you can then utilize the `NoopArtifactStore` on both methods: store and get

2023-11-16 22:58 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreStorer.java
> +public interface ArtifactStoreStorer {
Good point.

2023-11-16 22:59 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/NoopArtifactStoreStorer.java
> +public class NoopArtifactStoreStorer implements ArtifactStoreStorer {
In case we have a properly configured (but disabled) s3 artifact store, we use NoopArtifactStoreStorer along with S3ArtifactStoreGetter.

2023-11-16 23:00 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStore.java
> +public final class S3ArtifactStore {
OK, but where?

2023-11-16 23:03 UTC, xibz commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/NoopArtifactStoreStorer.java
> +public class NoopArtifactStoreStorer implements ArtifactStoreStorer {
I just meant in relation to the comment below where if you dont have a proper s3 config, you cant get either. So should probably noop that as well and potentially warn on no s3 config

2023-11-18 16:15 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
> +  public S3ArtifactStoreStorer s3ArtifactStoreStorer(
https://github.com/spinnaker/kork/pull/1120/commits/af4c8c891a56f0ee618b936d5fcacc13561f6232

2023-11-18 16:15 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
> +  public NoopArtifactStoreStorer noopArtifactStoreStorer() {
https://github.com/spinnaker/kork/pull/1120/commits/af4c8c891a56f0ee618b936d5fcacc13561f6232

2023-11-18 16:15 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
> +  public S3ArtifactStoreGetter s3ArtifactStoreGetter(
https://github.com/spinnaker/kork/pull/1120/commits/af4c8c891a56f0ee618b936d5fcacc13561f6232

2023-11-18 16:15 UTC, dbyron-sf commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/NoopArtifactStoreStorer.java
> +public class NoopArtifactStoreStorer implements ArtifactStoreStorer {
https://github.com/spinnaker/kork/pull/1120/commits/af4c8c891a56f0ee618b936d5fcacc13561f6232

2023-11-20 20:50 UTC, xibz commented on kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStore.java
> +public final class S3ArtifactStore {
I think we can move this to an enum, but it does not have to be this PR. I have a couple upcoming PRs where I can do that

2023-11-20 20:53 UTC, xibz approved these changes
Thanks for all the changes @dbyron-sf! Especially dealing with all the flags! Good work :). This looks good.

We were thinking of making this a bug fix and backporting it as well? I wonder if we should also mention it in the changelogs as this is technically a breaking change with the new `type` needing to be set.

2023-11-20 21:05 UTC, merged