feat(SpEL): implement to configure the limit of characters for SpEL expressions
spinnaker/kork pull request #1193
Opened 2024-06-26 14:27 UTC by j-sandy

Spring Expression Lanuage (SpEL) has a default limit of 10,000 characters. Springframework provides the feature to configure the limit. This feature allows to configure the limit of characters for SpEL expressions.

Approach:
In order to use an expression with characters more than the given default limit, require to follow either of the below approaches:
1. For Springframework >=5.3.28 and <6.1.3, by setting `maximumExpressionLength` field while instantiating the custom `SpelParserConfiguration` class. 
https://github.com/spring-projects/spring-framework/issues/30380 
https://github.com/spring-projects/spring-framework/issues/30446
2. For Springframework >=6.1.3, by setting a JVM system property or Spring property named `spring.context.expression.maxLength` to the maximum expression length needed by your application. 
https://github.com/spring-projects/spring-framework/issues/31952 
https://github.com/spring-projects/spring-framework/commit/785598629abda944343a02307ad82a79bb31b589 

Spinnaker supports spring boot 2.7.18, that brings springframework 5.3.31 [https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/dependency-versions.html#appendix.dependency-versions.propertie9]. So first approach need to be implemented along with spinnaker enhancement to expose the `maximumExpressionLength` field.

2024-06-26 16:48 UTC, dbyron-sf requested changes

2024-06-26 17:27 UTC, j-sandy commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
> +  private int maxExpressionLength;
Updated the code.

2024-06-26 17:31 UTC, dbyron-sf commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
> +  private int maxExpressionLength = -1;
javadoc please.

2024-07-01 15:08 UTC, dbyron-sf commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
> +  /** To set the maximum limit of characters in expression for SpEL evaluation. */
Please mention something about what -1 means.  I think it means use the limit from spring (e.g. 10000), as opposed to no limit.

2024-07-01 17:45 UTC, dbyron-sf approved these changes

2024-07-01 17:46 UTC, dbyron-sf commented
@mergifyio update

2024-07-02 17:50 UTC, merged