feat(credentials): Add credential abstraction
spinnaker/kork pull request #775
Opened 2020-09-04 18:42 UTC by ncknt

This is the first part of the work related to https://github.com/spinnaker/governance/blob/master/rfc/account-management.md.

It adds the concept of `Credentials`, `CredentialsRepository` that stores credentials of a given type, as well as bricks to populate and manage these credentials:
- `CredentialsDefinition` is the data with which we can build `Credentials`. It's optional but most implementation have them deserialized from yaml/json/something else.
- `CredentialsDefinitionSource` represents a source of definitions. By default, it's a getter on a Spring configuration object. It is pluggable and could make external calls - or just read a local file.
- `CredentialsParser` take a definition and transforms it into `Credentials`. It typically wires Spinnaker internals to do so (e.g. using Spring managed beans)
- `AbstractCredentialsLoader` keeps a source in sync with a repository. `BaseCredentialsLoader` does it by getting the full credentials list and comparing what is in the repository. Another possible implementation could be event based (receiving changes from an external system).

Finally, the `poller` package provides a way to frequently poll a credentials loader using Spring scheduled tasks.

2020-09-08 16:49 UTC, ncknt commented
@robzienert would you mind taking a look?

2020-09-08 18:53 UTC, robzienert requested changes
Changes:

- Add `package-info.java` files that set up `@NonnullByDefault`, and add `@Nullable` where needed.

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CompositeCredentialsRepository.java
> +    if (accountName == null || accountName.equals("")) {
Could be `Strings.isEmptyOrNull()`?

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CompositeCredentialsRepository.java
> +      throw new IllegalArgumentException("No credentials of type '" + type + "' found");
Please make use of `SpinnakerException` and its child exception classes, making subclasses where it makes sense.

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/Credentials.java
> +  String getType();
Need docs. What's the difference between these two, what are they used for?

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CredentialsLifecycleHandler.java
> +   * Credentials have been added. This is called before credentials are available in @{@link
```suggestion
   * Credentials have been added. This is called before credentials are available in {@link
```

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CredentialsLifecycleHandler.java
> +   * Credentials have been added. This is called before credentials are available in @{@link
This change should be applied to the other areas this happens, too.

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CredentialsRepository.java
> +  String getType();
Docs on interfaces and their methods, as well as any classes that do not implement an interface and cannot inherit the docs from a parent.

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/MapBackedCredentialsRepository.java
> +  protected Map<String, T> credentials = new HashMap<>();
Are we at risk of concurrent modification issues by having this just be a `HashMap`?

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/definition/AbstractCredentialsLoader.java
> +  public abstract void load();
Docs would be useful here. Since the return value is `void`, I'm having to assume each implementor would be responsible for adding the final loaded credentials into the `CredentialsRepository` themselves?

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/definition/BasicCredentialsLoader.java
> +  protected final Map<String, T> loadedDefinitions = new HashMap<>();
Also curious about concurrency here.

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/kork-credentials.gradle
> +  testImplementation "org.spockframework:spock-spring"
You're not using Spock (yay!), don't need these deps.

2020-09-08 18:53 UTC, robzienert commented on kork-credentials/kork-credentials.gradle
> +  api "com.fasterxml.jackson.core:jackson-annotations"
Avoid `api` scope when possible. We're trying to be more mindful of transient dependencies.

Also, Jackson isn't even used in this PR, so it can be removed.

2020-09-08 19:16 UTC, cfieber commented
I'm curious why we are adding a kork-credentials module instead of adding this in clouddriver. What other services do you expect to use this library in?

2020-09-08 19:18 UTC, ncknt commented
@cfieber Igor and Kayenta mainly.

2020-09-08 19:19 UTC, ncknt commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CompositeCredentialsRepository.java
> +      throw new IllegalArgumentException("No credentials of type '" + type + "' found");
I had copied the `IllegalArgumentException` from https://github.com/spinnaker/clouddriver/blob/master/clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/ArtifactCredentialsRepository.java#L49 and tried to keep the same unchecked exception for backward compatibility. Adding a new exception for that.

2020-09-08 19:25 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/definition/AbstractCredentialsLoader.java
> +  public abstract void load();
I think it may be an improvement, actually, to do `public <? extends Credentials> load()` and just handle the wiring in `Poller`, this would remove some boilerplate from implementations of `CredentialsLoader` (and wouldn't require an abstract class, which is a big win), and would improve the testability of `CredentialsLoader` implementations: Just assert on the response instead of mocking / verifying interactions with the `CredentialsRepository`.

2020-09-08 19:50 UTC, ncknt commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/MapBackedCredentialsRepository.java
> +  protected Map<String, T> credentials = new HashMap<>();
Yes, thanks!

2020-09-08 20:59 UTC, ncknt commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/definition/AbstractCredentialsLoader.java
> +  public abstract void load();
`load()` loads all credentials of a given type (e.g. all AWS accounts) in the repository. The default (`BasicCredentialsLoader`) implementation takes an account source (by default a getter on a Spring config object) -> passes it in a parser -> (we get a collection of `Credentials`) -> applies differences to the repository. It's simple to use for services using it, e.g. for k8s:

```
  public AbstractCredentialsLoader<KubernetesNamedAccountCredentials> kubernetesCredentialsLoader(
      KubernetesConfigurationProperties configurationProperties,
      KubernetesCredentials.Factory credentialFactory,
      CredentialsRepository<KubernetesNamedAccountCredentials> kubernetesCredentialsRepository) {
    return new BasicCredentialsLoader<>(
        configurationProperties::getAccounts,
        a -> new KubernetesNamedAccountCredentials(a, credentialFactory),
        kubernetesCredentialsRepository);
  }
```

The abstract class provides room for other implementations. For example, an event based implementation can query an external system and get responses such as `account X removed` or `new account Y added`. We have one implementation like that but it's hard to make generic enough to be included here.

The advantage for the developer of such an implementation is that the lifecycle (e.g. `add agent A and B`)  and the Spinnaker internal considerations (wire these beans to create Credentials) are separate and can evolve with each release without requiring maintenance of the associated plugin.

2020-09-08 21:11 UTC, ncknt commented
Updated the PR. I also added a check to make sure we only store credentials of the right type in a repository.

2020-09-11 20:48 UTC, claymccoy approved these changes
LGTM, it looks like you have resolved or responded to the other feedback and this seems like a useful approach.

2020-09-11 21:11 UTC, ncknt commented
I missed the comment about `NonnullByDefault`, updated now

2020-09-14 19:13 UTC, robzienert approved these changes
Just some small stuff I'd like to see changed before it goes in - looks marvelous aside.

2020-09-14 19:13 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CompositeCredentialsRepository.java
> +      throw new IllegalArgumentException(
Would be useful to move to `SpinnakerException` family for all exceptions. There's a number of places in the PR that need to change beyond this one point. Also happy to explain this (or doc if I haven't) why it's beneficial to do so.

2020-09-14 19:13 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/definition/AbstractCredentialsLoader.java
> +  public abstract void load();
This is helpful, thanks. I think it would be beneficial to capture this reasoning in the abstract class docs.

2020-09-14 19:13 UTC, robzienert commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/poller/Poller.java
> + * A poller attempts to reload credentials from its source at a regular interval.
How is the interval configured? For sake of docs, I see it's done via `PollerConfiguration` here - even just `{@link PollerConfiguration}` would be valuable.

2020-09-14 21:30 UTC, ncknt commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CompositeCredentialsRepository.java
> +      throw new IllegalArgumentException(
Oh I thought you had +1'd the backward compatibility of raising `IllegalArgumentException`. I like the typed exceptions.

2020-09-14 21:50 UTC, ncknt commented on kork-credentials/src/main/java/com/netflix/spinnaker/credentials/poller/Poller.java
> + * A poller attempts to reload credentials from its source at a regular interval.
Added comments (`credentials.poller.<type of creds>.reloadFrequencyMs` -> `credentials.poller.default.reloadFrequencyMs`) + `credentials.poller.enabled`.

2020-09-14 23:42 UTC, merged