Support additional partitions
spinnaker/kork pull request #868
Opened 2021-07-10 00:00 UTC by dbyron-sf

2021-07-10 06:30 UTC, xibz requested changes

2021-07-10 06:30 UTC, xibz commented on kork-aws/src/main/java/com/netflix/spinnaker/kork/aws/ARN.java
> +  static final Pattern PATTERN =
Why do we need to parse the ARN? The AWS SDK for Java has `Arn.fromString(someArn)`. The Java SDK doesn't do as deep of a validation especially on partition, but I think that makes sense and we should loosen this a little bit and just the `fromString`.

2021-07-11 16:17 UTC, dbyron-sf commented on kork-aws/src/main/java/com/netflix/spinnaker/kork/aws/ARN.java
> +  static final Pattern PATTERN =
Makes sense to me: https://github.com/spinnaker/kork/pull/868/commits/a4ea6472c0eabd4cff468df76e43af0d5e9ad5d0

2021-07-11 16:28 UTC, xibz approved these changes
Cool! I like these changes a lot more as this allows AWS to add more partitions and not have us constantly update this file.

2021-07-11 16:56 UTC, dbyron-sf commented
Yeah, was thinking the same.  Now I think we need an official approver to give a thumbs up.  Any suggestions?

2021-07-13 22:18 UTC, allisaurus approved these changes
Hooray use of `com.amazonaws.arn.Arn`! These changes LGTM re: arn/partition format and testing, but I haven't messed with KORK myself aside from the occasional rote AWS SDK version bump, so would like like to deter final approval to someone who's been more active here...

@danielpeach, do you see any reason these changes might not be good to go?

2021-07-13 23:03 UTC, link108 approved these changes

2021-07-13 23:04 UTC, merged

2021-07-14 02:40 UTC, dbyron-sf commented
Thanks for the review @allisaurus!