fix(dependencies): upgrade dependency google-auth-library-oauth2-http
spinnaker/kork pull request #976
Opened 2022-08-29 08:12 UTC by kirangodishala

With the implementation of secret manager (https://github.com/spinnaker/spinnaker/issues/6666), there is a need to upgrade the version of google-auth-library-oauth2-http library which was introduced as part of gcs secret engine implementation. With the removal of the this dependency constraint, GCS secret engine continue to work without any issue.

2022-08-29 09:24 UTC, j-sandy commented
As google secret manager support feature has been merged and marked for 1.29.x release [here](https://github.com/spinnaker/kork/pull/960). This PR also required to be marked for 1.29.x release.

2022-08-29 15:29 UTC, dbyron-sf requested changes
If it's really true that we need some newer version of `com.google.auth:google-auth-library-oauth2-http` (and please update the commit message to say which one we're getting, and what brings it in), it would be great to have a test that fails to demonstrate this, either in kork or in clouddriver.  If this PR is "just" bumping to a newer version, but doesn't actually fix anything, please change the commit message to `chore` instead of `fix`.

2022-08-29 17:55 UTC, kirangodishala commented
@dbyron-sf - SecretManagerServiceClient.create() throws below error with com.google.auth:google-auth-library-oauth2-http:0.18.0 constrain, because the method createWithUseJwtAccessWithScope() doesn't exist in ServiceAccountCredentials. This error can't be produced in a test as the credentials need to be supplied for that.    

```'com.google.auth.oauth2.ServiceAccountCredentials com.google.auth.oauth2.ServiceAccountCredentials.createWithUseJwtAccessWithScope(boolean)'
java.lang.NoSuchMethodError: 'com.google.auth.oauth2.ServiceAccountCredentials com.google.auth.oauth2.ServiceAccountCredentials.createWithUseJwtAccessWithScope(boolean)'
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:101)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:168)
	at com.google.cloud.secretmanager.v1.stub.GrpcSecretManagerServiceStub.create(GrpcSecretManagerServiceStub.java:248)
...
```

2022-08-29 17:59 UTC, dbyron-sf commented
Some kind of mock/fake credentials aren't sufficient?

2022-08-29 20:45 UTC, kirangodishala commented
Added a test in clouddriver. Here is the PR:  https://github.com/spinnaker/clouddriver/pull/5773

2022-08-30 16:32 UTC, j-sandy commented
With the proposed change of removing the constraint on google-auth-library-oauth2-http, the dependency get upgraded to version 1.6.0 as transitive dependency of [com.google.cloud:libraries-bom:25.3.0](https://mvnrepository.com/artifact/com.google.cloud/libraries-bom/25.3.0).
Tested all the major spinnaker services (clouddriver, orca, gate, igor, echo, halyard, front50, fiat, rosco) locally with updated kork, found successful build and passed all the test cases.
Dependency  insights before and after:
Clouddriver before changes:
```
> Task :clouddriver-web:dependencyInsight
com.google.auth:google-auth-library-oauth2-http:0.18.0
   variant "runtime" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-runtime
      org.gradle.libraryelements         = jar
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint
      - Forced

com.google.auth:google-auth-library-oauth2-http:0.18.0
+--- io.spinnaker.kork:kork-bom:7.145.0
|    +--- runtimeClasspath
|    +--- project :clouddriver-kubernetes
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-ecs
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-lambda
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-appengine
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-cloudfoundry
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-google
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-artifacts
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-kubernetes (*)
|    |    +--- project :clouddriver-ecs (*)
|    |    +--- project :clouddriver-lambda (*)
|    |    +--- project :clouddriver-appengine (*)
|    |    +--- project :clouddriver-cloudfoundry (*)
|    |    \--- project :clouddriver-google (*)
|    +--- project :clouddriver-elasticsearch
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-sql-mysql
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-sql-postgres
|    |    \--- runtimeClasspath
|    +--- project :cats:cats-sql
|    |    +--- project :clouddriver-sql-mysql (*)
|    |    \--- project :clouddriver-sql-postgres (*)
|    +--- project :clouddriver-sql
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-sql-mysql (*)
|    |    +--- project :clouddriver-sql-postgres (*)
|    |    \--- project :cats:cats-sql (*)
|    +--- project :clouddriver-tencentcloud
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-titus
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-aws
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-ecs (*)
|    |    +--- project :clouddriver-lambda (*)
|    |    \--- project :clouddriver-titus (*)
|    +--- project :clouddriver-eureka
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-tencentcloud (*)
|    |    +--- project :clouddriver-titus (*)
|    |    \--- project :clouddriver-aws (*)
|    +--- project :clouddriver-oracle
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-azure
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-consul
|    |    +--- runtimeClasspath
|    |    \--- project :clouddriver-google (*)
|    +--- project :clouddriver-huaweicloud
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-yandex
|    |    \--- runtimeClasspath
|    +--- project :clouddriver-docker
|    |    +--- runtimeClasspath
|    |    \--- project :clouddriver-cloudfoundry (*)
|    +--- project :clouddriver-core
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-kubernetes (*)
|    |    +--- project :clouddriver-ecs (*)
|    |    +--- project :clouddriver-lambda (*)
|    |    +--- project :clouddriver-appengine (*)
|    |    +--- project :clouddriver-cloudfoundry (*)
|    |    +--- project :clouddriver-google (*)
|    |    +--- project :clouddriver-artifacts (*)
|    |    +--- project :clouddriver-elasticsearch (*)
|    |    +--- project :cats:cats-sql (*)
|    |    +--- project :clouddriver-sql (*)
|    |    +--- project :clouddriver-tencentcloud (*)
|    |    +--- project :clouddriver-titus (*)
|    |    +--- project :clouddriver-aws (*)
|    |    +--- project :clouddriver-eureka (*)
|    |    +--- project :clouddriver-oracle (*)
|    |    +--- project :clouddriver-azure (*)
|    |    +--- project :clouddriver-consul (*)
|    |    +--- project :clouddriver-huaweicloud (*)
|    |    +--- project :clouddriver-yandex (*)
|    |    \--- project :clouddriver-docker (*)
|    +--- project :clouddriver-security
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-kubernetes (*)
|    |    +--- project :clouddriver-ecs (*)
|    |    +--- project :clouddriver-lambda (*)
|    |    +--- project :clouddriver-appengine (*)
|    |    +--- project :clouddriver-cloudfoundry (*)
|    |    +--- project :clouddriver-google (*)
|    |    +--- project :clouddriver-elasticsearch (*)
|    |    +--- project :cats:cats-sql (*)
|    |    +--- project :clouddriver-tencentcloud (*)
|    |    +--- project :clouddriver-titus (*)
|    |    +--- project :clouddriver-aws (*)
|    |    +--- project :clouddriver-oracle (*)
|    |    +--- project :clouddriver-azure (*)
|    |    +--- project :clouddriver-huaweicloud (*)
|    |    +--- project :clouddriver-yandex (*)
|    |    +--- project :clouddriver-docker (*)
|    |    \--- project :clouddriver-core (*)
|    +--- project :cats:cats-redis
|    |    +--- project :cats:cats-sql (*)
|    |    \--- project :clouddriver-core (*)
|    +--- project :cats:cats-core
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-kubernetes (*)
|    |    +--- project :clouddriver-ecs (*)
|    |    +--- project :clouddriver-lambda (*)
|    |    +--- project :clouddriver-appengine (*)
|    |    +--- project :clouddriver-cloudfoundry (*)
|    |    +--- project :clouddriver-google (*)
|    |    +--- project :cats:cats-sql (*)
|    |    +--- project :clouddriver-sql (*)
|    |    +--- project :clouddriver-tencentcloud (*)
|    |    +--- project :clouddriver-titus (*)
|    |    +--- project :clouddriver-aws (*)
|    |    +--- project :clouddriver-eureka (*)
|    |    +--- project :clouddriver-oracle (*)
|    |    +--- project :clouddriver-azure (*)
|    |    +--- project :clouddriver-huaweicloud (*)
|    |    +--- project :clouddriver-yandex (*)
|    |    +--- project :clouddriver-docker (*)
|    |    +--- project :clouddriver-core (*)
|    |    +--- project :clouddriver-security (*)
|    |    \--- project :cats:cats-redis (*)
|    +--- project :clouddriver-google-common
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-appengine (*)
|    |    \--- project :clouddriver-google (*)
|    +--- project :clouddriver-configserver
|    |    +--- runtimeClasspath
|    |    +--- project :clouddriver-kubernetes (*)
|    |    \--- project :clouddriver-aws (*)
|    +--- project :clouddriver-saga
|    |    +--- project :clouddriver-titus (*)
|    |    +--- project :clouddriver-aws (*)
|    |    \--- project :clouddriver-core (*)
|    +--- project :clouddriver-event
|    |    +--- project :clouddriver-sql (*)
|    |    \--- project :clouddriver-saga (*)
|    \--- project :clouddriver-api
|         +--- runtimeClasspath
|         +--- project :clouddriver-kubernetes (*)
|         +--- project :clouddriver-ecs (*)
|         +--- project :clouddriver-lambda (*)
|         +--- project :clouddriver-appengine (*)
|         +--- project :clouddriver-cloudfoundry (*)
|         +--- project :clouddriver-google (*)
|         +--- project :clouddriver-artifacts (*)
|         +--- project :clouddriver-elasticsearch (*)
|         +--- project :cats:cats-sql (*)
|         +--- project :clouddriver-sql (*)
|         +--- project :cl [...]

2022-08-30 16:37 UTC, j-sandy commented
Orca before change:
```
> Task :orca-web:dependencyInsight
com.google.auth:google-auth-library-oauth2-http:0.18.0
   variant "runtime" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-runtime
      org.gradle.libraryelements         = jar
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint
      - Forced

com.google.auth:google-auth-library-oauth2-http:0.18.0
+--- io.spinnaker.kork:kork-bom:7.145.0
|    +--- runtimeClasspath
|    +--- project :orca-echo
|    |    \--- runtimeClasspath
|    +--- project :orca-qos
|    |    \--- runtimeClasspath
|    +--- project :orca-queue-redis
|    |    \--- runtimeClasspath
|    +--- project :orca-queue-sql
|    |    \--- runtimeClasspath
|    +--- project :orca-sql-mysql
|    |    \--- runtimeClasspath
|    +--- project :orca-sql-postgres
|    |    \--- runtimeClasspath
|    +--- project :orca-sql
|    |    +--- runtimeClasspath
|    |    +--- project :orca-queue-sql (*)
|    |    +--- project :orca-sql-mysql (*)
|    |    \--- project :orca-sql-postgres (*)
|    +--- project :orca-queue
|    |    +--- runtimeClasspath
|    |    +--- project :orca-echo (*)
|    |    +--- project :orca-qos (*)
|    |    +--- project :orca-queue-redis (*)
|    |    +--- project :orca-queue-sql (*)
|    |    \--- project :orca-sql (*)
|    +--- project :keiko-redis-spring
|    |    +--- project :orca-queue-redis (*)
|    |    \--- project :orca-queue-sql (*)
|    +--- project :keiko-spring
|    |    +--- runtimeClasspath
|    |    +--- project :orca-queue (*)
|    |    \--- project :keiko-redis-spring (*)
|    +--- project :orca-applications
|    |    \--- runtimeClasspath
|    +--- project :orca-clouddriver-provider-titus
|    |    \--- runtimeClasspath
|    +--- project :orca-keel
|    |    +--- runtimeClasspath
|    |    \--- project :orca-applications (*)
|    +--- project :orca-igor
|    |    +--- runtimeClasspath
|    |    +--- project :orca-echo (*)
|    |    \--- project :orca-keel (*)
|    +--- project :orca-integrations-cloudfoundry
|    |    \--- runtimeClasspath
|    +--- project :orca-kayenta
|    |    \--- runtimeClasspath
|    +--- project :orca-mine
|    |    \--- runtimeClasspath
|    +--- project :orca-pipelinetemplate
|    |    \--- runtimeClasspath
|    +--- project :orca-clouddriver
|    |    +--- runtimeClasspath
|    |    +--- project :orca-applications (*)
|    |    +--- project :orca-clouddriver-provider-titus (*)
|    |    +--- project :orca-igor (*)
|    |    +--- project :orca-integrations-cloudfoundry (*)
|    |    +--- project :orca-kayenta (*)
|    |    +--- project :orca-mine (*)
|    |    \--- project :orca-pipelinetemplate (*)
|    +--- project :orca-bakery
|    |    +--- runtimeClasspath
|    |    \--- project :orca-clouddriver (*)
|    +--- project :orca-deploymentmonitor
|    |    +--- runtimeClasspath
|    |    \--- project :orca-clouddriver (*)
|    +--- project :orca-dry-run
|    |    +--- runtimeClasspath
|    |    \--- project :orca-echo (*)
|    +--- project :orca-flex
|    |    \--- runtimeClasspath
|    +--- project :orca-migration
|    |    \--- runtimeClasspath
|    +--- project :orca-redis
|    |    +--- runtimeClasspath
|    |    \--- project :orca-queue-redis (*)
|    +--- project :orca-front50
|    |    +--- runtimeClasspath
|    |    +--- project :orca-echo (*)
|    |    +--- project :orca-qos (*)
|    |    +--- project :orca-applications (*)
|    |    +--- project :orca-igor (*)
|    |    +--- project :orca-pipelinetemplate (*)
|    |    +--- project :orca-clouddriver (*)
|    |    +--- project :orca-bakery (*)
|    |    +--- project :orca-migration (*)
|    |    \--- project :orca-redis (*)
|    +--- project :orca-integrations-gremlin
|    |    \--- runtimeClasspath
|    +--- project :orca-interlink
|    |    +--- runtimeClasspath
|    |    \--- project :orca-sql (*)
|    +--- project :orca-peering
|    |    \--- runtimeClasspath
|    +--- project :orca-remote-stage
|    |    \--- runtimeClasspath
|    +--- project :orca-webhook
|    |    \--- runtimeClasspath
|    +--- project :orca-retrofit
|    |    +--- project :orca-echo (*)
|    |    +--- project :orca-applications (*)
|    |    +--- project :orca-keel (*)
|    |    +--- project :orca-igor (*)
|    |    +--- project :orca-kayenta (*)
|    |    +--- project :orca-mine (*)
|    |    +--- project :orca-pipelinetemplate (*)
|    |    +--- project :orca-clouddriver (*)
|    |    +--- project :orca-bakery (*)
|    |    +--- project :orca-deploymentmonitor (*)
|    |    +--- project :orca-flex (*)
|    |    +--- project :orca-front50 (*)
|    |    \--- project :orca-integrations-gremlin (*)
|    +--- project :orca-kotlin
|    |    +--- project :orca-queue (*)
|    |    +--- project :orca-kayenta (*)
|    |    +--- project :orca-dry-run (*)
|    |    \--- project :orca-integrations-gremlin (*)
|    +--- project :orca-core
|    |    +--- runtimeClasspath
|    |    +--- project :orca-echo (*)
|    |    +--- project :orca-qos (*)
|    |    +--- project :orca-queue-redis (*)
|    |    +--- project :orca-queue-sql (*)
|    |    +--- project :orca-sql (*)
|    |    +--- project :orca-queue (*)
|    |    +--- project :orca-applications (*)
|    |    +--- project :orca-clouddriver-provider-titus (*)
|    |    +--- project :orca-keel (*)
|    |    +--- project :orca-igor (*)
|    |    +--- project :orca-integrations-cloudfoundry (*)
|    |    +--- project :orca-kayenta (*)
|    |    +--- project :orca-mine (*)
|    |    +--- project :orca-pipelinetemplate (*)
|    |    +--- project :orca-clouddriver (*)
|    |    +--- project :orca-bakery (*)
|    |    +--- project :orca-deploymentmonitor (*)
|    |    +--- project :orca-dry-run (*)
|    |    +--- project :orca-flex (*)
|    |    +--- project :orca-migration (*)
|    |    +--- project :orca-redis (*)
|    |    +--- project :orca-front50 (*)
|    |    +--- project :orca-integrations-gremlin (*)
|    |    +--- project :orca-interlink (*)
|    |    +--- project :orca-peering (*)
|    |    +--- project :orca-remote-stage (*)
|    |    +--- project :orca-webhook (*)
|    |    +--- project :orca-retrofit (*)
|    |    \--- project :orca-kotlin (*)
|    +--- project :keiko-sql
|    |    \--- project :orca-queue-sql (*)
|    +--- project :keiko-redis
|    |    \--- project :keiko-redis-spring (*)
|    +--- project :keiko-core
|    |    +--- project :orca-sql (*)
|    |    +--- project :orca-queue (*)
|    |    +--- project :keiko-spring (*)
|    |    +--- project :keiko-sql (*)
|    |    \--- project :keiko-redis (*)
|    \--- project :orca-api
|         +--- runtimeClasspath
|         +--- project :orca-queue (*)
|         +--- project :orca-clouddriver-provider-titus (*)
|         +--- project :orca-clouddriver (*)
|         +--- project :orca-remote-stage (*)
|         +--- project :orca-webhook (*)
|         \--- project :orca-core (*)
\--- io.spinnaker.kork:kork-secrets-gcp:7.145.0
     +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
     \--- io.spinnaker.kork:kork-runtime:7.145.0
          +--- runtimeClasspath (requested io.spinnaker.kork:kork-runtime)
          \--- io.spinnaker.kork:kork-bom:7.145.0 (*)

com.google.auth:google-auth-library-oauth2-http:1.6.0 -> 0.18.0
\--- com.google.cloud:google-cloud-secretmanager:2.1.7
     +--- io.spinnaker.kork:kork-bom:7.145.0
     |    +--- runtimeClasspath
     |    +--- project :orca-echo
     |    |    \--- runtimeClasspath
     |    +--- project :orca-qos
     |    |    \--- runtimeClasspath
     |    +--- project :orca-queue-redis
     |    |    \--- runtimeClasspath
     |    +--- project :orca-queue-sql
     |    |    \--- runtimeClasspath
     |    +--- project :orca-sql-mysql
     |    |    \--- runtimeClasspath
    [...]

2022-08-30 16:47 UTC, j-sandy commented
Interestingly, front50 is using a strictly constrained version of same dependency with version 0.20.0 [here] (https://github.com/spinnaker/front50/blob/0932db218695b61c4559b9950089c22a188eab83/front50-gcs/front50-gcs.gradle#L27).
So, the change in kork did not affect it.
front50 before change:
```
> Task :front50-web:dependencyInsight
com.google.auth:google-auth-library-oauth2-http:0.20.0
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]
   Selection reasons:
      - Forced
      - By constraint

com.google.auth:google-auth-library-oauth2-http:0.20.0
+--- project :front50-gcs
|    \--- runtimeClasspath
\--- com.google.cloud:google-cloud-storage:1.108.0
     +--- project :front50-gcs (*)
     \--- io.spinnaker.kork:kork-bom:7.145.0 (requested com.google.cloud:google-cloud-storage:2.6.1)
          +--- runtimeClasspath
          +--- project :front50-migrations
          |    \--- runtimeClasspath
          +--- project :front50-azure
          |    \--- runtimeClasspath
          +--- project :front50-gcs (*)
          +--- project :front50-oracle
          |    \--- runtimeClasspath
          +--- project :front50-redis
          |    \--- runtimeClasspath
          +--- project :front50-s3
          |    \--- runtimeClasspath
          +--- project :front50-swift
          |    \--- runtimeClasspath
          +--- project :front50-sql
          |    \--- runtimeClasspath
          +--- project :front50-core
          |    +--- runtimeClasspath
          |    +--- project :front50-migrations (*)
          |    +--- project :front50-azure (*)
          |    +--- project :front50-gcs (*)
          |    +--- project :front50-oracle (*)
          |    +--- project :front50-redis (*)
          |    +--- project :front50-s3 (*)
          |    +--- project :front50-swift (*)
          |    \--- project :front50-sql (*)
          +--- project :front50-api
          |    +--- runtimeClasspath
          |    +--- project :front50-migrations (*)
          |    +--- project :front50-azure (*)
          |    +--- project :front50-gcs (*)
          |    +--- project :front50-oracle (*)
          |    +--- project :front50-redis (*)
          |    +--- project :front50-s3 (*)
          |    +--- project :front50-swift (*)
          |    +--- project :front50-sql (*)
          |    \--- project :front50-core (*)
          +--- project :front50-sql-mysql
          |    \--- project :front50-sql (*)
          \--- project :front50-sql-postgres
               \--- project :front50-sql (*)

com.google.auth:google-auth-library-oauth2-http:0.18.0 -> 0.20.0
+--- io.spinnaker.kork:kork-bom:7.145.0
|    +--- runtimeClasspath
|    +--- project :front50-migrations
|    |    \--- runtimeClasspath
|    +--- project :front50-azure
|    |    \--- runtimeClasspath
|    +--- project :front50-gcs
|    |    \--- runtimeClasspath
|    +--- project :front50-oracle
|    |    \--- runtimeClasspath
|    +--- project :front50-redis
|    |    \--- runtimeClasspath
|    +--- project :front50-s3
|    |    \--- runtimeClasspath
|    +--- project :front50-swift
|    |    \--- runtimeClasspath
|    +--- project :front50-sql
|    |    \--- runtimeClasspath
|    +--- project :front50-core
|    |    +--- runtimeClasspath
|    |    +--- project :front50-migrations (*)
|    |    +--- project :front50-azure (*)
|    |    +--- project :front50-gcs (*)
|    |    +--- project :front50-oracle (*)
|    |    +--- project :front50-redis (*)
|    |    +--- project :front50-s3 (*)
|    |    +--- project :front50-swift (*)
|    |    \--- project :front50-sql (*)
|    +--- project :front50-api
|    |    +--- runtimeClasspath
|    |    +--- project :front50-migrations (*)
|    |    +--- project :front50-azure (*)
|    |    +--- project :front50-gcs (*)
|    |    +--- project :front50-oracle (*)
|    |    +--- project :front50-redis (*)
|    |    +--- project :front50-s3 (*)
|    |    +--- project :front50-swift (*)
|    |    +--- project :front50-sql (*)
|    |    \--- project :front50-core (*)
|    +--- project :front50-sql-mysql
|    |    \--- project :front50-sql (*)
|    \--- project :front50-sql-postgres
|         \--- project :front50-sql (*)
\--- io.spinnaker.kork:kork-secrets-gcp:7.145.0
     +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
     \--- io.spinnaker.kork:kork-runtime:7.145.0
          +--- runtimeClasspath (requested io.spinnaker.kork:kork-runtime)
          \--- io.spinnaker.kork:kork-bom:7.145.0 (*)

com.google.auth:google-auth-library-oauth2-http:1.6.0 -> 0.20.0
+--- com.google.api:gax:2.16.0
|    +--- io.spinnaker.kork:kork-bom:7.145.0
|    |    +--- runtimeClasspath
|    |    +--- project :front50-migrations
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-azure
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-gcs
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-oracle
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-redis
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-s3
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-swift
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-sql
|    |    |    \--- runtimeClasspath
|    |    +--- project :front50-core
|    |    |    +--- runtimeClasspath
|    |    |    +--- project :front50-migrations (*)
|    |    |    +--- project :front50-azure (*)
|    |    |    +--- project :front50-gcs (*)
|    |    |    +--- project :front50-oracle (*)
|    |    |    +--- project :front50-redis (*)
|    |    |    +--- project :front50-s3 (*)
|    |    |    +--- project :front50-swift (*)
|    |    |    \--- project :front50-sql (*)
|    |    +--- project :front50-api
|    |    |    +--- runtimeClasspath
|    |    |    +--- project :front50-migrations (*)
|    |    |    +--- project :front50-azure (*)
|    |    |    +--- project :front50-gcs (*)
|    |    |    +--- project :front50-oracle (*)
|    |    |    +--- project :front50-redis (*)
|    |    |    +--- project :front50-s3 (*)
|    |    |    +--- project :front50-swift (*)
|    |    |    +--- project :front50-sql (*)
|    |    |    \--- project :front50-core (*)
|    |    +--- project :front50-sql-mysql
|    |    |    \--- project :front50-sql (*)
|    |    \--- project :front50-sql-postgres
|    |         \--- project :front50-sql (*)
|    +--- com.google.cloud:google-cloud-storage:1.108.0 (requested com.google.api:gax:1.56.0)
|    |    +--- project :front50-gcs (*)
|    |    \--- io.spinnaker.kork:kork-bom:7.145.0 (requested com.google.cloud:google-cloud-storage:2.6.1) (*)
|    +--- com.google.cloud:google-cloud-core-http:2.6.0
|    |    +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
|    |    \--- com.google.cloud:google-cloud-storage:1.108.0 (requested com.google.cloud:google-cloud-core-http:1.93.4) (*)
|    +--- com.google.cloud:google-cloud-core:2.6.0
|    |    +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
|    |    +--- com.google.cloud:google-cloud-storage:1.108.0 (requested com.google.cloud:google-cloud-core:1.93.4) (*)
|    |    \--- com.google.cloud:google-cloud-core-http:2.6.0 (*)
|    +--- com.google.cloud:google-cloud-secretmanager:2.1.7
|    |    +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
|    |    \--- io.spinnaker.kork:kork-secrets-gcp:7.145.0
|    |         +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
|    |         \--- io.spinnaker.kork:kork-runtime:7.145.0
|    |              +--- runtimeClasspath (requested io.spinnaker.kork:kork-runtime)
|    |              \--- io.spinnaker.kork:kork-bom:7.145.0 (*)
|    \--- com.google.api:gax-httpjson:0.101.0
|         +--- io.spinnaker.kork:kork-bom:7.145.0 (*)
|         \--- com.goog [...]

2022-08-30 18:41 UTC, dbyron-sf commented
Excellent.  Thanks @j-sandy .  Seems like all that's left here is to update the commit message with information about the new version:

> version 1.6.0 as transitive dependency of [com.google.cloud:libraries-bom:25.3.0](https://mvnrepository.com/artifact/com.google.cloud/libraries-bom/25.3.0).

and we're there...with possibly a follow-up PR to front50?  Please let me know if you're planning one of those and I'll be on the lookout.

2022-08-30 20:25 UTC, kirangodishala commented
@dbyron-sf - updated the commit message

2022-08-30 21:02 UTC, dbyron-sf approved these changes

2022-08-30 21:05 UTC, merged

2022-08-30 21:27 UTC, dbyron-sf commented
I'd like to hold off tagging kork until we get kayenta tests passing on master.  See https://spinnakerteam.slack.com/archives/C0DPVDMQE/p1661532962948339