fix(expression): add doNotEval method to restrict expressions evaluation for an object.
spinnaker/kork pull request #978
Opened 2022-09-23 14:01 UTC by armory-abedonik

**What?**

Spinnaker supports [the expression functions](https://github.com/spinnaker/kork/blob/a4617ed929ca34a2216449425ab5b54b5ac271d5/kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java#L55) e.g. `toJson`, `toBase64`, `fromBase64` and other. At the moment, `toJson` method [throws an exception](https://github.com/spinnaker/kork/blob/a4617ed929ca34a2216449425ab5b54b5ac271d5/kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java#L198-L200) for valid JSON when `${}` expression is defined as a string value

```java
String converted = mapper.writeValueAsString(o);
if (converted != null && converted.contains("${")) {
  throw new SpelHelperFunctionException("result for toJson cannot contain an expression");
}
```

We have a use case where `toJson` method needs to convert such objects without any errors:

```json
{
  "owner": "managed-by-${team}"
}
```

**Solution**:
Introduce a new SpEL `doNotEval` method that wraps incoming JSON object with `NotEvaluableExpression` class.

Usage:

```
${#toJson(#doNotEval(#stage('Terraform Show').outputs.status.outputs.show.planfile_json))}
```

2022-09-27 18:41 UTC, xibz requested changes
Thanks for the changes @armory-abedonik. I think this does most of what we talked about with a few changes being needed. :)

2022-09-27 18:41 UTC, xibz commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +    public static NotEvaluableExpression doNotEval(Object o) {
This type needs to be added to the [allowed return list](https://github.com/spinnaker/kork/blob/master/kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java#L73-L87)

2022-09-27 18:41 UTC, xibz commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +        if (o instanceof NotEvaluableExpression) {
I think this is still an issue with anything reprocessing the stage. If you have some stage that calls `toJson`, then any subsequent stage will cause this expression to be evaluated. We need to ensure even through reprocessing of this stage's data doesn't re-evaluate it's SpEL, otherwise it needs to remain the no eval type. Maybe some more testing there to ensure.

2022-09-27 18:41 UTC, xibz commented on kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
> +public class ExpressionsSupportTest {
We need a test that evaluates the `doNotEval` expression directly. We need something like
```
Collections.singletonMap("owner", "managed-by-${#doNotEval('${team}')");
```

or something of that nature. I believe this test would have caught the allowed return types being missed

2022-09-27 18:41 UTC, xibz commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/NotEvaluableExpression.java
> +public class NotEvaluableExpression {
Can we get some documentation explaining the point of this class? More so why someone would see this in their spinnaker pipelines and how to go about evaluating it.

2022-09-27 18:41 UTC, xibz commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +                new FlowExpressionFunctionProvider(),
`FlowExpressionFunctionProvider` is a really odd name. Maybe `SpELEvalSkipFunctionProvider`?

2022-09-29 12:37 UTC, armory-abedonik commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +                new FlowExpressionFunctionProvider(),
If use `FlowExpressionFunctionProvider` then we can add other flow management expressions in the future e.g. `evalIfCondition`, `evalIfPositive` etc...

2022-09-29 12:39 UTC, armory-abedonik commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +    public static NotEvaluableExpression doNotEval(Object o) {
I've tested the behaviour and it worked even without it... Maybe I messed something... Adderd.

2022-09-29 12:46 UTC, armory-abedonik commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +        if (o instanceof NotEvaluableExpression) {
As you know, almost all spinnaker users don't use unresolved SpEL here. Only 1% of users do something crazy... In this way they can use `doNotEval` method, and they should take care that the next stages are processed correctly. I don't think that we can cover all possible use cases here.

2022-09-29 13:19 UTC, armory-abedonik commented on kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
> +public class ExpressionsSupportTest {
A new unit test based on `ExpressionTransform` class has been added. Btw, we don't support such `"managed-by-${#doNotEval('${team}')"` use case because `doNotEval` returns an object (not a string).

2022-09-29 16:29 UTC, armory-abedonik commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/NotEvaluableExpression.java
> +public class NotEvaluableExpression {
sure, added

2022-09-29 17:52 UTC, xibz commented on kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
> +public class ExpressionsSupportTest {
That was copy pasta, but yea, just adding a test for `#doNotEval` from the expression parser is what I meant.
```
Collections.singletonMap("owner", "${#doNotEval('${team}')}");
```
We just need to ensure that the object that is returned is returned properly, and then we can even pass that along to a `toJson` call.

2022-09-29 18:00 UTC, xibz commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +        if (o instanceof NotEvaluableExpression) {
Yes, I think we have two use cases here. Users who want to remove the `doNotEval` when evaluating `toJson` and users who may want to keep `doNotEval` when calling `toJson`. It may be nice to put some metadata in `doNotEval` so it decides how it's evaluated rather than having it live in `toJson`. Like 
```
doNotEval('${someExpression}', 'toJsonRemoval')
```
maybe even having it as a boolean might work, but I can see other stages may needing this same kind of flexibility. We may need to think about this some. The one thing I dislike is having users know string specifics, like `toJsonRemove`, but if enums can be used in SpEL, that can be useful. I haven't explored that though.

What do you think?

2022-09-29 18:05 UTC, armory-abedonik commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +        if (o instanceof NotEvaluableExpression) {
Could you share an example when and how it should be used. I'm not sure that got you correctly...

2022-09-29 18:21 UTC, xibz commented on kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
> +        if (o instanceof NotEvaluableExpression) {
My thinking is a user making a webhook call (maybe this webhook is outside metrics or something) with `toJson` and `doNotEval` which funnels back to Spinnaker. That seems like a valid use case, but the `toJson` that has the SpEL will be re-evaluated and thus returning the value. The main question is are we okay with that?

2022-09-29 18:27 UTC, xibz approved these changes

2022-10-05 15:25 UTC, dogonthehorizon commented
We'll want to add this to the [SpEL docs](https://spinnaker.io/docs/reference/pipeline/expressions/#helper-functions) but also need to wait until it's released. Noting this here for now and creating an issue in our team's backlog to address.

2022-10-05 15:25 UTC, dogonthehorizon approved these changes

2022-10-07 18:14 UTC, merged

2022-10-19 15:20 UTC, dogonthehorizon commented
Going to backport this first to 1.28/29 branches quickly followed by backports for https://github.com/spinnaker/kork/pull/981 so that they're appropriately feature flagged

2022-10-19 15:23 UTC, dogonthehorizon commented
@mergifyio backport release-1.28.x release-1.29.x

2022-10-25 10:08 UTC, armory-abedonik commented
@mergify backport release-1.27.x